APRS_SERVER_HOST = 'aprs.glidernet.org'
APRS_SERVER_PORT_FULL_FEED = 10152
APRS_SERVER_PORT_CLIENT_DEFINED_FILTERS = 14580

APRS_APP_NAME = 'ogn-gateway-python'
APRS_APP_VER = '0.2'

APRS_KEEPALIVE_TIME = 240
