"""pareto: int -> float

Revision ID: dfade4709ef9
Revises: f69d3839a4e4
Create Date: 2021-12-19 14:28:16.757143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfade4709ef9'
down_revision = 'f69d3839a4e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receiver_rankings', 'local_distance_pareto', type_=sa.FLOAT)
    op.alter_column('receiver_rankings', 'global_distance_pareto', type_=sa.FLOAT)
    # ### end Alembic commands ###


def downgrade():
     ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receiver_rankings', 'local_distance_pareto', type_=sa.INTEGER)
    op.alter_column('receiver_rankings', 'global_distance_pareto', type_=sa.INTEGER)
    # ### end Alembic commands ###
