"""Added sender_positions index for name-timestamp-error_count

Revision ID: f69d3839a4e4
Revises: 5413cb96c44d
Create Date: 2020-12-29 16:40:13.662995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f69d3839a4e4'
down_revision = '5413cb96c44d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_sender_positions_name_timestamp_error_count', 'sender_positions', ['name', 'timestamp', 'error_count'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sender_positions_name_timestamp_error_count', table_name='sender_positions')
    # ### end Alembic commands ###
